# Generated by Django 4.1.7 on 2023-04-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0003_alter_avaliacao_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='atracoes'),
        ),
    ]
